// Fetches the self-hosted web fonts and writes src/styles/fonts.css.
//
// Sources (the only two allowed by the brief):
//   Fontshare  — Boska, Zodiak, Switzer, General Sans, Erode (static woff2 per weight)
//   Google     — Jost (variable, latin subset as served by the CSS2 API)
//
// Run:  npm run fonts
// Needs network access to api.fontshare.com / cdn.fontshare.com and fonts.googleapis.com.
// If `pyftsubset` (python fonttools + brotli) is on PATH the Fontshare files are subset to
// Latin; otherwise they are kept whole (still fine, ~2x larger).
//
// The script is idempotent and only writes @font-face rules for files that exist, so a
// clone without network still builds — the token files fall back to system faces.
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'public/fonts';
const CSS_OUT = 'src/styles/fonts.css';
mkdirSync(OUT, { recursive: true });

const LATIN =
  'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD';

// family -> { fontshare slug, weights }  (Jost comes from Google below)
const FONTSHARE = {
  Switzer: { slug: 'switzer', weights: [200, 300, 400, 500] },
  'General Sans': { slug: 'general-sans', weights: [300, 400, 500] },
  Erode: { slug: 'erode', weights: [300, 400] },
};

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

async function getText(url) {
  const r = await fetch(url, { headers: { 'user-agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.text();
}
async function getBin(url, file) {
  const r = await fetch(url, { headers: { 'user-agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  writeFileSync(file, Buffer.from(await r.arrayBuffer()));
}

function fileFor(family, weight) {
  return `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}.woff2`;
}

let hasSubsetter = false;
try {
  execSync('pyftsubset --help', { stdio: 'ignore' });
  hasSubsetter = true;
} catch {}

// ---------- Fontshare ----------
const fsQuery = Object.values(FONTSHARE)
  .map((f) => `f[]=${f.slug}@${f.weights.join(',')}`)
  .join('&');
try {
  const css = await getText(`https://api.fontshare.com/v2/css?${fsQuery}&display=swap`);
  const blocks = css.match(/@font-face\s*{[^}]*}/g) ?? [];
  for (const b of blocks) {
    const family = b.match(/font-family:\s*'([^']+)'/)?.[1];
    const weight = Number(b.match(/font-weight:\s*(\d+)/)?.[1]);
    const style = b.match(/font-style:\s*(\w+)/)?.[1] ?? 'normal';
    const url = b.match(/url\(([^)]+\.woff2)\)/)?.[1];
    if (!family || !weight || !url || style !== 'normal') continue;
    const target = join(OUT, fileFor(family, weight));
    const raw = target.replace('.woff2', '.raw.woff2');
    await getBin(url, hasSubsetter ? raw : target);
    if (hasSubsetter) {
      execSync(
        `pyftsubset "${raw}" --flavor=woff2 --unicodes="${LATIN}" --layout-features='*' --output-file="${target}"`,
      );
      unlinkSync(raw);
    }
    console.log('fontshare', family, weight);
  }
} catch (e) {
  console.warn('Fontshare fetch failed (network policy?):', e.message);
}

// ---------- Google: Jost variable ----------
try {
  const css = await getText('https://fonts.googleapis.com/css2?family=Jost:wght@100..700&display=swap');
  const latin = css.match(/\/\* latin \*\/\s*@font-face\s*{[^}]*}/)?.[0];
  const url = latin?.match(/url\(([^)]+)\)/)?.[1];
  if (!url) throw new Error('no latin block');
  await getBin(url, join(OUT, 'jost-variable.woff2'));
  console.log('google Jost variable (latin)');
} catch (e) {
  console.warn('Google Fonts fetch failed:', e.message);
}

// ---------- write fonts.css from whatever exists ----------
const present = new Set(readdirSync(OUT).filter((f) => f.endsWith('.woff2')));
let out = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n@layer tokens {\n`;
if (present.has('jost-variable.woff2')) {
  out += `@font-face {\n  font-family: 'Jost';\n  font-style: normal;\n  font-weight: 100 700;\n  font-display: swap;\n  src: url('/fonts/jost-variable.woff2') format('woff2');\n  unicode-range: ${LATIN};\n}\n`;
}
for (const [family, f] of Object.entries(FONTSHARE)) {
  for (const w of f.weights) {
    const file = fileFor(family, w);
    if (!present.has(file)) continue;
    out += `@font-face {\n  font-family: '${family}';\n  font-style: normal;\n  font-weight: ${w};\n  font-display: swap;\n  src: url('/fonts/${file}') format('woff2');\n  unicode-range: ${LATIN};\n}\n`;
  }
}
out += '}\n';
writeFileSync(CSS_OUT, out);
console.log('wrote', CSS_OUT, 'with', present.size, 'files');
